### ISSUE TITLE
Errors "Cannot set property 'visibility' of undefined" and "Cannot read property 'offsetTop' of undefined" in JS Console

### ISSUE THREAD

**Issue by osya** [bogenpirat/remote-torrent-adder#176]
Extension "Remote Torrent Adder" caused the following errors in JS console in Chrome:
```
 Uncaught TypeError: Cannot set property 'visibility' of undefined
     at chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-ui-1.10.3.custom.min.js:6:19111
     at chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-ui-1.10.3.custom.min.js:6:19343
     at chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-ui-1.10.3.custom.min.js:6:19347
 Uncaught TypeError: Cannot read property 'offsetTop' of undefined
     at XMLDocument.<anonymous> (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/fancybox/jquery.fancybox.pack.js:46:5)
     at l (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-2.0.3.min.js:4:24882)
     at Object.fireWith [as resolveWith] (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-2.0.3.min.js:4:25702)
     at Function.ready (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-2.0.3.min.js:4:2900)
     at S (chrome-extension://oabphaconndgibllomdcjbfdghcmenci/miscapis/jquery-2.0.3.min.js:4:553)
```

**Comment by bogenpirat** [comment]
is this with rutorrent and the label/directory interactivity on?

looks like it's not showing up for me on a page i tested, does it show up for you only on specific sites?

**Comment by osya** [comment]
Yes, these errors appears not for all sites. For example, it appears for the www.redfoodie.com. But not appears for example for site ya.ru. I don't use rutorrent. I don't know what is "the label/directory interactivity on" - please let me know how to check it.

**Comment by bogenpirat** [comment]
404a211 should address this.
